AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'bin/*'
    - Gemfile

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
